name: PyTest
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Setup Python
        uses: actions/checkout@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          poetry install
      - name: Run unit tests
        run: |
          make test
